ALTER TABLE FACT_SALES
ADD CONSTRAINT FK_FACT_SALES_OWNERSHIP FOREIGN KEY (OwnershipId) REFERENCES DIM_OWNERSHIP(Id),
ADD CONSTRAINT FK_FACT_SALES_ACTIVITY FOREIGN KEY (ActivityId) REFERENCES DIM_ACTIVITY(Id),
ADD CONSTRAINT FK_FACT_SALES_FUNCTION FOREIGN KEY (FunctionId) REFERENCES DIM_FUNCTION(Id),
ADD CONSTRAINT FK_FACT_SALES_STRUCTURE FOREIGN KEY (StructureId) REFERENCES DIM_STRUCTURE(Id),
ADD CONSTRAINT FK_FACT_SALES_SITE FOREIGN KEY (SiteId) REFERENCES DIM_SITE(Id),
ADD CONSTRAINT FK_FACT_SALES_LANDCLASS FOREIGN KEY (LandClassId) REFERENCES DIM_LANDCLASS(Id),
ADD CONSTRAINT FK_FACT_SALES_LOCATION FOREIGN KEY (LocationId) REFERENCES DIM_LOCATION(Id),
ADD CONSTRAINT FK_FACT_SALES_BUILD_YEAR FOREIGN KEY (BuildYearId) REFERENCES DIM_BUILD_YEAR(Id),
ADD CONSTRAINT FK_FACT_SALES_BILLING FOREIGN KEY (BillingId) REFERENCES DIM_BILLING(Id),
ADD CONSTRAINT FK_FACT_SALES_SALE_DATE FOREIGN KEY (SaleDateId) REFERENCES DIM_SALE_DATE(Id);
